=== barcia/ivan.gal/_data/podcast_galego.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/product.schema.json",
    "title": "Podcast",
    "description": "Podcast list",
    "type": "array",
    "items": {
        "type": "object",
        "description": "Podcast",
        "properties": {
            "title": {
              "description": "Podcast title",
              "type": "string"
            },
            "description": {
              "description": "Podcast description",
              "type": "string",
              "maxLength": 140
            },
            "image": {
              "description": "Podcast image",
              "type": "string",
              "pattern": "^https?://(?:[a-z0-9-]+.)+[a-z]{2,6}(?:/[^/#?]+)+.(?:jpg|jpeg|webp|avifgif|png)$"
            },
            "tags": {
              "description": "Podcast tags. Min. 1 and max. 3",
              "type": "array",
              "minItems": 1,
              "maxItems": 3,
              "uniqueItems": true,
              "items": {
                  "type": "string",
                  "enum": ["lingua", "politica", "tecnoloxia"]
              }
            },
            "feed_url": {
              "description": "Podcast URL feed",
              "type": "string",
              "pattern": "^https?://(?:[a-z0-9-]+.)+[a-z]{2,6}(?:/[^/#?]+)+.(?:xml)$"
            },
            "status": {
              "description": "Podcast status",
              "type": "string",
              "default": "active",
              "enum": ["active", "inactive", "undefined"]
            },
            "links": {
              "description": "Podcast social links",
              "type": "array",
              "uniqueItems": true,
              "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                      "link": {
                          "type": "string",
                          "description": "Podcast link",
                          "enum": ["web", "twitter", "facebook"]
                      },
                      "url": {
                          "description": "Podcasts link URL",
                          "type": "string",
                          "pattern": "(https?://)?([w-])+.{1}([a-zA-Z]{2,63})([/w-]*)*/???([^#nr]*)?#?([^nr]*)"
                      }
                  },
                  "required": ["link", "url"]
              }
            },
            "platforms": {
              "description": "Podcast platforms links",
              "type": "array",
              "uniqueItems": true,
              "items": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                      "platform": {
                          "type": "string",
                          "description": "Podcast platform name",
                          "enum": ["apple", "google", "spotify", "ivoox"]
                      },
                      "url": {
                          "description": "Podcasts platform URL",
                          "type": "string",
                          "pattern": "https?://(www.)?[-a-zA-Z0-9@:%._+~#=]{1,256}.[a-zA-Z0-9()]{1,6}b([-a-zA-Z0-9()@:%_+.~#?&//=]*)"
                      }
                  },
                  "required": ["platform", "url"]
              }
            }
          },
          "required": ["title", "image", "tags", "feed_url", "status"]
    }
}

=== barcia/ivan.gal/_data/podcast_galego.json
[
    {
        "title": "O podcast primeiro",
        "description": "Long podcast description",
        "image": "https://myimage.gal/pic.png",
        "tags": ["lingua"],
        "feed_url": "https://feed.gal/feed.xml",
        "links": [
            {
                "link": "twitter",
                "url": "sdsafda"
            }
        ],
        "platforms": [
            {
                "platform": "apple",
                "url": "https://feed.gal/feed.xml"
            },
            {
                "platform": "apple",
                "url": "https://feed.gal/feed.xml"
            }
        ],
        "status": "active"
    },
    {
        "title": "O podcast segundo",
        "description": "Long podcast description",
        "image": "https://myimage.gal/pic.png",
        "tags": ["lingua"],
        "feed_url": "https://feed.gal/feed.xml",
        "links": [
            {
                "link": "twitter",
                "url": "sdsafda"
            }
        ],
        "platforms": [
            {
                "platform": "apple",
                "url": "https://feed.gal/feed.xml"
            },
            {
                "platform": "apple",
                "url": "https://feed.gal/feed.xml"
            }
        ],
        "status": "active"
    }
]
